# coding: utf-8
# AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
# Generated by ./devscripts/make_misskey_instance_list.py
from __future__ import unicode_literals

instances = {
    # list of instances here
    "misskey.io",
}

__all__ = ['instances']
