from __future__ import unicode_literals

import subprocess
import os
import re

# git rev-parse --short master
sp = subprocess.Popen(
    ['git', 'rev-parse', '--short', 'master'],
    stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    cwd=os.path.dirname(os.path.abspath(__file__)))
out, err = sp.communicate()
out = out.decode().strip()

git_commit = ''
if re.match('[0-9a-f]+', out):
    git_commit = out


# git rev-parse --short youtube-dl
sp = subprocess.Popen(
    ['git', 'rev-parse', '--short', 'youtube-dl'],
    stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    cwd=os.path.dirname(os.path.abspath(__file__)))
out, err = sp.communicate()
out = out.decode().strip()

git_upstream_commit = ''
if re.match('[0-9a-f]+', out):
    git_upstream_commit = out

pycode = '''# coding: utf-8
# AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
# Generated by ./devscripts/make_buildconfig.py
from __future__ import unicode_literals

# git rev-parse --short master
git_commit = '%s'

# git rev-parse --short youtube-dl
git_upstream_commit = '%s'

''' % (git_commit, git_upstream_commit)

with open('./youtube_dl/build_config.py', 'w') as w:
    w.write(pycode)
