# coding: utf-8
from __future__ import unicode_literals, print_function

import sys
import subprocess

sys.path[:0] = ['.']

from youtube_dl.utils import int_or_none


results = set()

minimum_version = (88, 0, 0, 0)  # mark 88.0.0.0 as minimum version
# https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning
with subprocess.Popen(
        ['git', '-c', 'versionsort.suffix=-', 'ls-remote',
         '--tags', '--sort=v:refname', 'https://chromium.googlesource.com/chromium/src'],
        stdout=subprocess.PIPE,) as proc:
    for line in proc.stdout:
        commit_hash, tag_ref = line.strip().decode().split('\t')
        tag_name = tag_ref[10:]  # trim first "refs/tags/"
        version_tuple = tuple(int_or_none(x) for x in tag_name.split('.') if x.isdigit())
        if len(version_tuple) < 4:
            continue
        if version_tuple < minimum_version:
            continue
        results.add(tag_name)

pycode = '''# coding: utf-8
# AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
# Generated by ./devscripts/make_chrome_version_list.py
# This list is created from git tags in https://chromium.googlesource.com/chromium/src
from __future__ import unicode_literals

versions = [
    # list of instances here
    "%s"
]

__all__ = ['versions']
''' % '",\n    "'.join(sorted(results))

with open('./youtube_dl/chrome_versions.py', 'w') as w:
    w.write(pycode)
